### ISSUE TITLE
Event listeners don't get cleaned up after calling .destroy()

### ISSUE THREAD

**Issue by Neo-Oli** [julianna-langston/chartjs2music#149]
Hi

The event listeners for key presses don't get cleaned up when calling [.destroy()](https://www.chartjs.org/docs/latest/developers/api.html#destroy). This will cause the dialogs menus to stack. If we called `destroy()` and `new Chart()` on the same canvas 3 times it, pressing `h` will open the help dialog 3 times.

Since we're using our chart.js charts inside of a React component. It will get rendered and destroyed multiple times, especially in development contexts.

![2024-03-27_17_31_39_srksch11](https://github.com/julianna-langston/chartjs2music/assets/7983745/3841a829-6bb5-40ed-880d-18d8f6e46e3e)

I [implemented](https://www.redcross.ch/en/ic-report-2021) chart(js)2music now and noticed a few bugs. So that's why I am creating several issues, but overall I'm quite happy with the plugin. :heart:

**Comment by julianna-langston** [comment]
Thank you for finding this issue!

Event listeners and dialogs will now get cleaned up after you call `.destroy()`. This feature is available in v0.5.0, which has already been published.

Let me know if you need anything else!
