### ISSUE TITLE
TS Lint Error: TS7016: Could not find a declaration file for module chartjs-plugin-chart2music

### ISSUE THREAD

**Issue by melwynfurtado** [julianna-langston/chartjs2music#171]
Firstly, thanks for this wonderful plugin!

Can we please add typings to the distribution so that I can get rid of the error `TS7016: Could not find a declaration file for module chartjs-plugin-chart2music.` ?

I tried to open a PR with the change as its bare minimum but had some auth issues pushing the branch.

🙏🏼

**Comment by julianna-langston** [comment]
Thanks for your issue and your kind words!

I was able to reproduce your issue. I just published v0.5.1, which has a .d.ts file in it. This fixed the issue in my reproduction, so I hope it works for you. 

This was a minimal TS change, just to address the TS7016 error. If you have any other issues, please let me know!
