### ISSUE TITLE
Visual Sync for Seaborn Line Plot Data

### ISSUE THREAD

**Issue by Ankita-Khiratkar** [julianna-langston/chartjs2music#35]
### Description
I am using c2m library to produce sonification for the line plot of Python's data visualization library Seaborn. I can successfully generate the sonification for all data points, but I am struggling to achieve the visual sync as there is only one path for the whole line in the HTML. 

### Resources
a. I am producing a line plot using this [basic example](https://seaborn.pydata.org/generated/seaborn.lineplot.html).
b. Stored the generated plot in SVG format using the default function of matplotlib.pyplot and assigned id as MyChart to it
c. Imported this SVG and wrote the necessary c2m code for producing the sonification of line plot

### Expected Behavior
The sonification should be properly synchronized with the highlighting of the specific html #path of the Seaborn line plot with the usage of arrow keys used for interacting with the map. Each data point should get highlighted while navigating through the line chart, along with the sound for that.

### Actual Behavior
Sonification with respect to all data points works perfectly on arrow keys. The whole line is represented in one path html element. Hence not able to change the color for a specific data point while navigating.

This is a single-line chart
I need help adding code from c2m to highlight data points when only one path element is present in HTML. 
a. Is there a way to add markers from the onFocusCallback function that will get highlighted while navigating?
b. Is it possible to rotate the x-ticks while displaying the line chart like we can format them before displaying? 

HTML Template
[lineplot_sonification.txt](https://github.com/julianna-langston/chartjs2music/files/11826658/lineplot_sonification.txt)

### Reproduction Steps:
a. Download the above lineplot_sonification.txt and save it as an HTML file
b. Open this HTML and try the sonification for seaborn lineplot

**Comment by julianna-ciq** [comment]
I updated the script tag. This implementation is specific to the structure of this particular page, and may not work on other line charts produced by seaborn.

```js
    // Get list of coordinates for the line
    const coordinates = document.querySelector("#line2d_14 path").getAttribute("d").trim().split("\n").map((str) => str.substring(2).trim().split(" ").map((n) => +n));

    // Create a circle element to go over the first point in the line
    const circle = document.createElementNS("http://www.w3.org/2000/svg", "circle");
    circle.setAttribute("cx", coordinates[0][0]);
    circle.setAttribute("cy", coordinates[0][1]);
    circle.setAttribute("r", "5");
    circle.setAttribute("fill", "cyan");

    // Add the circle element to the chart
    document.querySelector("#figure_1").appendChild(circle);

    const x = [1949, 1950, 1951, 1952, 1953, 1954, 1955, 1956, 1957, 1958, 1959, 1960];
    const {err} = c2mChart({
        type: "line",
        element: document.getElementById("MyChart"),
        cc: document.getElementById("cc"),
        axes: {
            x: {
                label: "class",
                format: (index) => x[index]
            },
            y: {
                label: "count",
                minimum: 0
            }
        },
        data: [121, 125, 172, 183, 229, 234, 270, 318, 355, 363, 420, 472],
        options: {
            onFocusCallback: ({index}) => {
                // Get the coordinates of the current point on the line, and move the circle to those coordinates
                circle.setAttribute("cx", coordinates[index][0]);
                circle.setAttribute("cy", coordinates[index][1]);
            }
        }
    });
    if(err){
        console.error(err);
    }
```
