### ISSUE TITLE
Keyboard arrows skip first data point

### ISSUE THREAD

**Issue by andrewz-skyward** [julianna-langston/chartjs2music#90]
With focus on a chart, pressing the right arrow should navigate to the first data point on the chart.  Instead, the first data point is skipped and the second data point is navigated to.  If a chart only has a single data point, it is not possible to navigate the chart using the keyboard.

**Comment by julianna-langston** [comment]
We just release v0.1.5, and now the tooltip will automatically pop up when the user first tabs to a chart. This way, for keyboard-only users, the tooltip will always be visible whenever they're focused on the chart. I hope this makes for an easier user experience for you and your users.

I hope that helps!

**Comment by andrewz-skyward** [comment]
Thank you for your work, I really enjoy this plugin.  I don't think the provided solution entirely fixes what I perceive the issue to be though.  It would be nice if the first data point would only be focused into when use the arrow keys or some other kind of keyboard interaction other than focus being on the chart.  This would bring consistency to what is displayed in the CC element.  Currently, when focus is on the chart initially, the CC element contains the summary of the chart ("Sonified Chart ..."). At the same time, the first data point is also considered to be active (pressing spacebar plays the sound).  I'd suggest that when focus is first placed on the chart that no data points should be active until keyboard interaction is made to navigate to a data point.  So, when a user presses an arrow key such as the right arrow, the first data point will be active and the tooltip will then display and the CC element will contain the value for the data point.  As it is now, the CC element will always show the "Sonified Chart ..." text if a chart only has a single data point.  

Thank you again for all your work on this plugin!
