### ISSUE TITLE
Tooltip remains open on chart after tabbing away from the chart

### ISSUE THREAD

**Issue by andrewz-skyward** [julianna-langston/chartjs2music#91]
When navigating the data points of a chart using the arrow keys, the tooltip is displayed for the current data point (as expected).  When pressing TAB to navigate away from the chart, the tooltip for the last data point visited remains visible.

**Comment by julianna-langston** [comment]
Thank you for reporting this issue! I'm working on a fix for this now.

**Comment by julianna-langston** [comment]
This has been fixed in v0.1.5. Now, when you navigate away from the chart, the tooltip hides itself. Additionally, when you first navigate to the chart, the tooltip will immediately appear.

Please let us know if you find any other issues!
